# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quilt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('pic', models.ImageField(upload_to='')),
                ('quiltID', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
